### ISSUE TITLE
Bug Fixing - Phase 2

### ISSUE THREAD

**Issue by ifirmawan** [sabirudev/redmetric-frontend#16]
## Todo

- [x] Judul "Forgot Password" Pop up setelah registrasi.
- [x] Update Profil member belum bisa.
- [x] Implementasi end point Logout ```{{app_base_url}}/api/membership/logout```.
