### ISSUE TITLE
Revisi Dashboard Juri

### ISSUE THREAD

**Issue by ifirmawan** [sabirudev/redmetric-frontend#27]
## Todo

- [x] Hapus menu dashboard.
- [x] Ganti nama menu List Juri diganti Penilaian.
- [x] Kolom tabel penilaian: No, Periode, Kelurahan, Total Points,  Aksi. 
- [x] Aksi memiliki 2 tombol : Lihat Detail, Edit (*jika masih draft). status draft adalah total_points === NULL.

![Screen Shot 2021-08-09 at 23 08 20](https://user-images.githubusercontent.com/20871229/128791559-76ca15c2-5c87-474b-8f3f-438aae145b0b.png)
