### ISSUE TITLE
Revisi Dashboard Admin

### ISSUE THREAD

**Issue by ifirmawan** [sabirudev/redmetric-frontend#28]
## Todo

- [x] Ganti menu Vilagers menjadi Kelurahan
- [x] Hapus tombol Add user
- [ ] Tambah filter pencarian dengan keyword.
- [x] Kolom Tabel kelurahan : No, E-mail, Kelurahan, Jumlah Submit, Aksi.
- [x] Ganti opsi Delete dengan Detail

![Screen Shot 2021-08-09 at 23 09 01](https://user-images.githubusercontent.com/20871229/128793028-e097e2b1-4848-4c37-90d0-c4ed4be5e6c2.png)
